apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
spec:
  type: NodePort
  ports:
    - nodePort: 30306
      port: 3306
      targetPort: 3306
      name: ${APP_NAME}
  selector:
    app: ${APP_NAME}
